name: publish

on:
  push:
    branches:
    - dockerhub
    
jobs:
  updateBranch:
    name: Update master branch 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: Embraser01/update-git-branch-action@v1.0.0
      if: github.ref == 'refs/heads/dockerhub'
      with:
        branch: master
        # force: 1 # To push-force to the branch
        githubToken: ${{ secrets.PAT_TOKEN }} # Github Token
